ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"

_ovirt:
  cluster_name: ovirt-jak-kr
  domain: "jtest.pivotal.io"
  major_version: "4"
  minor_version: "17"
  patch_version: "0"
  build_version: ""
  release_date: ""
  repo_url: ""
  download_url: "https://github.com/okd-project/okd/releases/download"
  download: false
  base_path: /root
  host_num: "{{ groups['all'] | length }}"
  local_home_dir: "/home/jomoon"
  dns: "192.168.2.199 8.8.8.8 168.126.63.1"
  download_client: false
  net:
    type: "virtual"                           # Or Physical
    gateway: "192.168.2.1"
    vipaddr: "192.168.1.79"
    ipaddr0: "192.168.0.17"
    ipaddr1: "192.168.1.17"
    ipaddr2: "192.168.2.17"
  client:
    net:
      type: "virtual"                         # Or Physical
      cores: 1
      ipaddr0: "192.168.0.17"
      ipaddr1: "192.168.1.17"
      ipaddr2: "192.168.2.17"
  ext_storage:
    net:
      ipaddr0: "192.168.0."
      ipaddr1: "192.168.1."
      ipaddr2: "192.168.2."
  vms:
    co9: [ "rk9-freeipa", "co9-node01", "co9-node02", "co9-node03", "co9-node04", "co9-node05", "co9-node06", "co9-node07" ]
    ubt24: [ "rk9-freeipa", "ubt24-node01", "ubt24-node02", "ubt24-node03", "ubt24-node04", "ubt24-node05" ]


_vmware:
  esxi_hostname: "192.168.0.231"
  esxi_username: "root"
  esxi_password: "Changeme34#$"


_kvm:
  hostname: "192.168.0.101"
  username: "root"
  password: "changeme"

