---
_dc:
  - { name: jDC01, compat_ver: "4.7", desc: "Jack's oVirt KR Datacenter", local: "false", quota: "disabled" }  # local is false means Shared Datacenter


_cluster:
  - { name: jClu01, dc: jDC01, cpu_type: 'Intel SandyBridge Family', compat_ver: "4.7", desc: "Jack's oVirt KR Cluster" }


_dns:
  zone:
    - { name: jtest.pivotal.io, type: forward }
    - { name: 2.168.192.in-addr.arpa, type: reverse }
  resource:
    forward:
      - {  name: "co9-node01",  zone: "jtest.pivotal.io",  type: "-a-rec",  value: "192.168.2.171"  }
      - {  name: "co9-node02",  zone: "jtest.pivotal.io",  type: "-a-rec",  value: "192.168.2.172"  }
      - {  name: "co9-node03",  zone: "jtest.pivotal.io",  type: "-a-rec",  value: "192.168.2.173"  }
      - {  name: "co9-node04",  zone: "jtest.pivotal.io",  type: "-a-rec",  value: "192.168.2.174"  }
      - {  name: "co9-node05",  zone: "jtest.pivotal.io",  type: "-a-rec",  value: "192.168.2.175"  }
      - {  name: "co9-node06",  zone: "jtest.pivotal.io",  type: "-a-rec",  value: "192.168.2.176"  }
      - {  name: "co9-node07",  zone: "jtest.pivotal.io",  type: "-a-rec",  value: "192.168.2.177"  }
      - {  name: "co9-node08",  zone: "jtest.pivotal.io",  type: "-a-rec",  value: "192.168.2.178"  }
    reverse:
      - { name: "171",  zone: 2.168.192.in-addr.arpa,  type: "--ptr-rec", value: "co9-node01.jtest.pivotal.io."  }
      - { name: "172",  zone: 2.168.192.in-addr.arpa,  type: "--ptr-rec", value: "co9-node02.jtest.pivotal.io."  }
      - { name: "173",  zone: 2.168.192.in-addr.arpa,  type: "--ptr-rec", value: "co9-node03.jtest.pivotal.io."  }
      - { name: "174",  zone: 2.168.192.in-addr.arpa,  type: "--ptr-rec", value: "co9-node04.jtest.pivotal.io."  }
      - { name: "175",  zone: 2.168.192.in-addr.arpa,  type: "--ptr-rec", value: "co9-node05.jtest.pivotal.io."  }
      - { name: "176",  zone: 2.168.192.in-addr.arpa,  type: "--ptr-rec", value: "co9-node06.jtest.pivotal.io."  }
      - { name: "177",  zone: 2.168.192.in-addr.arpa,  type: "--ptr-rec", value: "co9-node07.jtest.pivotal.io."  }
      - { name: "178",  zone: 2.168.192.in-addr.arpa,  type: "--ptr-rec", value: "co9-node08.jtest.pivotal.io."  }


_selinux:
  policy:
    - { name: httpd_can_network_connect, toggle: on }
    - { name: httpd_gracefull_shutdown, toggle: on }
    - { name: httpd_can_network_relay, toggle: on }
  semange:
    - { name: port , type: http_port, proto: tcp, port: 6443 }
    - { name: port , type: http_port, proto: tcp, port: 22623 }
    - { name: port , type: http_port, proto: tcp, port: 1936 }


_firewall:
  service:
    - { name: dns,    state: enabled }
    - { name: http,   state: enabled }
    - { name: https,  state: enabled }
  port:
    - { state: enabled, port: 6443, proto: tcp, zone: public }
    - { state: enabled, port: 1936, proto: tcp, zone: public }
    - { state: enabled, port: 8080, proto: tcp, zone: public }

