---
- name: Add Gluster Storage Domain
  ovirt_storage_domain:
    name: "{{ _sd.gluster.name }}"
    host: "{{ hostvars[groups['hosts'][0]].ansible_hostname }}"
    data_center: "{{ _dc[0].name }}"
    glusterfs:
      address: "{{ hostvars[groups['gluster'][0]].ansible_hostname }}"
      path: "/{{ _gluster.root_dir }}"
    auth: "{{ _ovirt.engine.auth }}"
    # mount_options: "backup-volfile-servers=co9-node01:co9-node02:co9-node03,_netdev 0 0"

