---
#- name: Connect iSCSI Target
#  ovirt_storage_connection:
#    storge: "{{ _sd.iscsi.name }}"
#    address: "{{ hostvars[groups['iscsi'][0]].ansible_ssh_host }}"
#    target: "{{ _iscsi.target.iqn }}:{{ _iscsi.target.os_version }}.{{ _iscsi.target.disks[0].name }}"
#    username: "{{ _iscsi.target.user }}"
#    password: "{{ _iscsi.target.password }}"
#    port: 3260
#    type: iscsi
#    auth: "{{ _ovirt.engine.auth }}"


- import_tasks: domain/iscsi/fail-get-lun-id.yml


- name: Unattached iSCSI Storage Domain
  ovirt_storage_domain:
    state: unattached
    name: "{{ _sd.iscsi.name }}"
    host: "{{ hostvars[groups['hosts'][1]].ansible_hostname }}"
    data_center: "{{ _dc[0].name }}"
    storage_format: v5
    wait: true
    iscsi:
      target: "{{ _iscsi.target.iqn }}:{{ _iscsi.target.os_version }}.{{ _iscsi.target.disks[0].name }}"
      lun_id:
        - "{{ oe_sd_lun_id }}"
      address: "{{ hostvars[groups['iscsi'][0]].ansible_ssh_host }}"
      port: 3260
      username: "{{ _iscsi.target.user }}"
      password: "{{ _iscsi.target.password }}"
    auth: "{{ _ovirt.engine.auth }}"


- name: Activate iSCSI Storage Domain
  ovirt_storage_domain:
    name: "{{ _sd.iscsi.name }}"
    host: "{{ hostvars[groups['hosts'][1]].ansible_hostname }}"
    data_center: "{{ _dc[0].name }}"
    wait: true
    state: present
    auth: "{{ _ovirt.engine.auth }}"


- name: Get iSCSI Storage Domain Info
  ovirt_storage_domain_info:
    pattern:
      name: "{{ _sd.iscsi.name }}"
    auth: "{{ _ovirt.engine.auth }}"
  register: storage_domain_details

