---
- name: Install Administration Tools
  package:
    name: "{{ item }}"
    state: present
  ignore_errors: yes
  register: install_admintool
  with_items:
    - "scsi-target-utils"
- debug: msg={{ install_admintool }}


- name: Creates Directory
  file:
    path: "{{ item.base_dir }}"
    state: directory
    mode: 0755
  register: create_dir
  with_items: "{{ _iscsi.target.disks }}"
- debug: msg={{ create_dir }}


- name: Create an Disk Images
  shell: |
    dd if=/dev/zero of={{ item.base_dir }}/{{ item.name }}.img count=0 bs=1 seek={{ item.size }}
  register: create_disk_images
  with_items: "{{ _iscsi.target.disks }}"
- debug: msg={{ create_disk_images }}


- name: Copy TGTd Config File
  template: src=target.conf.j2 dest=/etc/tgt/conf.d/target.conf owner=root group=root mode=644 force=yes
  register: copy_tgtd_conf
- debug: msg={{ copy_tgtd_conf }}


- name: Install PolicyCoreUtils Package
  package:
    name: "{{ item }}"
    state: present
  ignore_errors: yes
  register: install_policycoreutils
  with_items:
    - "policycoreutils-python-utils"
- debug: msg={{ install_policycoreutils }}


- name: Change SELinux Context
  shell: |
    chcon -R -t tgtd_var_lib_t "{{ item.base_dir }}"
  ignore_errors: yes
  register: change_selinux_chcon
  with_items: "{{ _iscsi.target.disks }}"
- debug: msg={{ change_selinux_chcon }}


- name: Change SELinux Context
  shell: |
    semanage fcontext -a -t tgtd_var_lib_t "{{ item.base_dir }}"
  ignore_errors: yes
  register: selinux_context_changed
  with_items: "{{ _iscsi.target.disks }}"
- debug: msg={{ selinux_context_changed}}


#- name: Start TGTd
#  shell: |
#    systemctl eanbled --now tgtd
#  register: start_tgtd
#- debug: msg={{ start_tgtd }}


- name: Enable and Start TGTd
  systemd:
    name: tgtd
    state: restarted
    enabled: true
    daemon-reload: true
  register: restart_tgtd
  until: restart_tgtd is succeeded
  retries: 3
  delay: 10
- debug: msg={{ restart_tgtd }}


- name: Verified the TGTd Status
  shell: |
    tgtadm --mode target --op show
  register: verify_tgtd
- debug: msg={{ verify_tgtd }}


- name: Allow iSCSI Target Service Port
  shell: |
    firewall-cmd --add-service=iscsi-target --permanent
  ignore_errors: true
  register: allow_iscsi_target
- debug: msg={{ allow_iscsi_target }}


- name: Reload Firewalld
  shell: |
    firewall-cmd --reload
  ignore_errors: true
  register: reload_firewalld
- debug: msg={{ reload_firewalld }}

