---
- name: Stop and Disable TGTd
  systemd:
    name: tgtd
    state: stopped
    enabled: no
    daemon-reload: yes
  register: stop_tgtd
  ignore_errors: true
#  until: stop_tgtd is succeeded
#  retries: 3
#  delay: 10
- debug: msg={{ stop_tgtd }}


- name: Disallow iSCSI Target Service Port
  shell: |
    firewall-cmd --remove-service=iscsi-target --permanent
  register: disallow_iscsi_target
  ignore_errors: true
- debug: msg={{ disallow_iscsi_target }}


- name: Reload Firewalld
  shell: |
    firewall-cmd --reload
  register: reload_firewalld
  ignore_errors: true
- debug: msg={{ reload_firewalld }}


- name: Uninstall iSCSI Target Utils Package for Less Version Than RHEL/CentOS/Rocky 8
  package:
    name: "{{ item }}"
    state: absent
  register: uninstall_scsi_pkgs
  ignore_errors: true
  with_items:
    - "scsi-target-utils"
    - "policycoreutils-python-utils"
- debug: msg={{ uninstall_scsi_pkgs }}


- name: Deleted an Added SELinux Context
  shell: |
    semanage fcontext -d "{{ item.base_dir }}"
  register: delete_selinux_context_disk_dir
  ignore_errors: true
  with_items: "{{ _iscsi.target.disks }}"
- debug: msg={{ delete_selinux_context_disk_dir }}


- name: Delete TGTd Config File for Less Version than RHEL/CentOS/Rocky 8
  file:
    path: "{{ item }}"
    state: absent
  register: delete_tgtd_conf
  ignore_errors: true
  with_items:
    - "/etc/tgt/conf.d/target.conf"
- debug: msg={{ delete_tgtd_conf }}


- name: Delete vDisk Files of TGTd
  file:
    path: "{{ item.base_dir }}/{{ item.name }}.img"
    state: absent
  register: delete_disk_images
  ignore_errors: true
  with_items: "{{ _iscsi.target.disks }}"
- debug: msg={{ disk_images_delete }}


- name: Delete Directory
  file:
    path: "{{ item.base_dir }}"
    state: absent
  register: delete_dir
  ignore_errors: true
  with_items: "{{ _iscsi.target.disks }}"
- debug: msg={{ delete_dir }}

