---
- name: Check OS ( oVirt )
  fail: msg="Not a Red Hat or SuSE based system!"
  when: ansible_os_family != 'RedHat' or  ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky'


- name: Set Facts For Network and Packages Informations
  import_tasks: set-ovirt-facts.yml
  tags: install, uninstall, deploy, destory, setup, remove, enable, disable, create, delete, add
  when: inventory_hostname in groups['ovirt']


- name: Import Repository and Packages Playbook
  import_tasks: pkgs/main.yml
  when: ( repo is defined and repo == true ) or ( pkgs is defined and pkgs == true )


- name: Create DataCenter
  import_tasks: create-datacenter.yml
  tags: create, install
  when: ( dc is defined and dc == true ) and inventory_hostname in groups['engine']


- name: Add Hosts
  import_tasks: add-hosts.yml
  tags: add, install
  when: ( host is defined and host == true ) and inventory_hostname in groups['engine']


- name: Import Storage Domain Playbook
  import_tasks: sd/main.yml
  when: ( nfs is defined and nfs == true ) or ( iscsi is defined and iscsi == true )


- name: Remove Hosts
  import_tasks: remove-hosts.yml
  tags: remove, uninstall
  when: ( host is defined and host == true ) and inventory_hostname in groups['engine']


- name: Delete DataCenter
  import_tasks: delete-datacenter.yml
  tags: delete, uninstall
  when: ( dc is defined and dc == true ) and inventory_hostname in groups['engine']


- name: Setup Ovirt Engine
  import_tasks: setup-ovirt-engine.yml
  tags: setup, deploy, install
  when: ( engine is defined and engine == true ) and inventory_hostname in groups['engine']


- name: Clean Ovirt Engine
  import_tasks: clean-ovirt-engine.yml
  tags: clean, destroy, uninstall
  when: ( engine is defined and engine == true ) and inventory_hostname in groups['engine']


- name: Setup NTP Service
  import_tasks: ext/setup-chrony.yml
  tags: setup, install
  when: ( ntp is defined and ntp == true )

