---
- name: Check OS ( oVirt )
  fail: msg="Not a Red Hat or SuSE based system!"
  when: ansible_os_family != 'RedHat' or  ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky'


- name: Set Facts For Network and Packages Informations
  import_tasks: set-ovirt-facts.yml
  tags: install, uninstall, deploy, destory, setup, remove, enable, disable, create, delete
  when: inventory_hostname in groups['ovirt']


- name: Enable oVirt Repository
  import_tasks: pkgs/enable-repo.yml
  tags: enable, setup, install
  when: ( repo is defined and repo == true ) and inventory_hostname in groups['ovirt']


- name: Install oVirt Packages
  import_tasks: pkgs/install-pkgs.yml
  tags: setup, install
  when: ( pkgs is defined and pkgs == true ) and inventory_hostname in groups['engine']


- name: Create DataCenter
  import_tasks: create-datacenter.yml
  tags: create, install
  when: ( dc is defined and dc == true ) and inventory_hostname in groups['engine']


- name: Delete DataCenter
  import_tasks: delete-datacenter.yml
  tags: delete, uninstall
  when: ( dc is defined and dc == true ) and inventory_hostname in groups['engine']


- name: Uninstall oVirt Packages
  import_tasks: pkgs/uninstall-pkgs.yml
  tags: remove, uninstall
  when: ( pkgs is defined and pkgs == true ) and inventory_hostname in groups['engine']


- name: Disable oVirt Repository
  import_tasks: pkgs/disable-repo.yml
  tags: disable, remove, uninstall
  when: ( repo is defined and repo == true ) and inventory_hostname in groups['ovirt']


- name: Setup NTP Service
  import_tasks: ext/setup-chrony.yml
  tags: setup, install
  when: ( ntp is defined and ntp == true )

