---
- name: Check OS ( oVirt )
  fail: msg="Not a Red Hat or SuSE based system!"
  when: ansible_os_family != 'RedHat' or  ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky'


- name: Set Facts For Network and Packages Informations
  import_tasks: set-ovirt-facts.yml
  tags: install, uninstall, deploy, destory, setup, remove, enable, disable, create, delete, add
  when: inventory_hostname in groups['engine'] or inventory_hostname in groups['hosts']


- name: Import Repository and Packages Playbook
  import_tasks: pkgs/main.yml
  when: ( repo is defined and repo == true ) or ( pkgs is defined and pkgs == true )


- name: Import Data Center Playbook
  import_tasks: dc/main.yml
  when: ( dc is defined and dc == true )


- name: Import Cluster Playbook
  import_tasks: cluster/main.yml
  when: ( cluster is defined and cluster == true )


- name: Import Host Playbook
  import_tasks: host/main.yml
  when: ( host is defined and host == true )


- name: Import oVirt Engine Playbook
  import_tasks: engine/main.yml
  when: ( engine is defined and engine == true )


- name: Setup NTP Service
  import_tasks: ext/setup-chrony.yml
  tags: setup, install
  when: ( ntp is defined and ntp == true )


- name: Setup oVirt Engine Python SDK
  import_tasks: ext/install-ovirt-sdk.yml
  tags: setup, install
  when: ( sdk is defined and sdk == true )

