---
- name: Add NFS Storage Domain
  ovirt_storage_domain:
    name: data_nfs
    host: co9-node02
    data_center: Default
    nfs:
      address: 192.168.2.177
      path: /ovirt-nfs-root
    storage_format: v5
    auth: "{{ _ovirt.engine.auth }}"

