---
- name: Add NFS Storage Domain
  ovirt_storage_domain:
    name: data_nfs
    host: co9-node02
    data_center: Default
    nfs:
      address: 192.168.2.177
      path: /ovirt-nfs-root
    storage_format: v5
    auth:
      hostname: co9-node01.jtest.pivotal.io
      username: admin@ovirt@internalsso
      password: changeme
      insecure: true

