---
- name: Check OS ( Network )
  fail: msg="Not a Red Hat or SuSE based system!"
  when: ansible_os_family != 'RedHat' or  ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky'


- name: Set Facts For Network and Packages Informations
  import_tasks: set-storage-facts.yml
  tags: install, uninstall, create, delete, setup, remove, clean, add


- name: Create Network
  import_tasks: create-network.yml
  tags: create
  when: ( net is defined and net == true ) and inventory_hostname in groups['engine']


- name: Delete Network
  import_tasks: delete-network.yml
  tags: delete
  when: ( net is defined and net == true ) and inventory_hostname in groups['engine']


