---
- name: Delete Local DNS Server
  lineinfile:
    dest: "/etc/resolv.conf"
    regexp: "^nameserver 127.0.0.1"
    state: absent
  register: delete_local_dns_server


# Change DNS setting
# Replace device name or IP address to your environment
- name: Rollback DNS Settings
  shell: |
    export DNS=$(nmcli device show {{ item.netdev_name }} | grep ^IP4.DNS | awk '{print $2}')
    nmcli connection modify {{ item.conn_name }} ipv4.dns "$DNS"
    nmcli connection modify {{ item.conn_name }} ipv4.dns-search "{{ _okd.domain }}"
    nmcli connection up {{ item.conn_name }}
  register: rollback_dns_settings
  with_items:
    - { dev_ip_addr: "{{ ipaddr0 }}", netdev_name: "{{ netdev0 }}", conn_name: conn0 }
    - { dev_ip_addr: "{{ ipaddr2 }}", netdev_name: "{{ netdev2 }}", conn_name: conn2 }
- debug: msg={{ rollback_dns_settings }}
  when: print_debug == true
  #  export DNS=$(nmcli device show {{ item.netdev_name }} | grep ^IP4.DNS | awk '{print $2}' | sed 1d)


- name: Rollback Required Settings for OKD Cluster to Systemd Resolved
  lineinfile:
    dest: "{{ item.file_name }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  register: add_required_config
  ignore_errors: true
  with_items:
    - { file_name: "/etc/systemd/resolved.conf",  regexp: "^DNS=*",  line: "#DNS=",  state: present }
    - { file_name: "/etc/resolv.conf",            regexp: "^search {{ _okd.domain }}",    line: "search {{ _okd.domain }}",    state: present }


- name: Uninstall Systemd Resolved Packages
  package:
    name: "{{ item }}"
    state: absent
  ignore_errors: true
  with_items:
    - "systemd-resolved"

