---
_iscsi:
  target:
    iqn: "iqn.2025-02.io.pivotal.jtest"
    user: iscsiadm
    password: changeme
    os_version: "co9"
    disks:
      - { name: "jtest-vdisk01", base_dir: "/data/iscsi01", size: "10G" }
      - { name: "jtest-vdisk02", base_dir: "/data/iscsi02", size: "10G" }
      - { name: "jtest-vdisk03", base_dir: "/data/iscsi03", size: "10G" }

