---
- name: Stop and Disable iSCSI Target
  systemd:
    name: target
    state: stopped
    enabled: no
    daemon-reload: yes
  register: stop_scsi_target
  ignore_errors: true
- debug: msg={{ stop_scsi_target }}


- name: Disallow iSCSI Target Service Port
  shell: |
    firewall-cmd --remove-service=iscsi-target --permanent
  register: disallow_iscsi_target
  ignore_errors: true
- debug: msg={{ disallow_iscsi_target }}


- name: Reload Firewalld
  shell: |
    firewall-cmd --reload
  register: reload_firewalld
  ignore_errors: true
- debug: msg={{ reload_firewalld }}


- name: Uninstall iSCSI Target and Relevant Packages
  package:
    name: "{{ item }}"
    state: absent
  register: uninstall_iscsi_pkgs
  ignore_errors: true
  with_items:
    - "target"
    - "policycoreutils-python-utils"
- debug: msg={{ uninstall_iscsi_pkgs }}


- name: Delete vDisk Files of TGTd
  file:
    path: "{{ item.base_dir }}/{{ item.name }}.img"
    state: absent
  register: delete_disk_images
  ignore_errors: true
  with_items: "{{ _iscsi.target.disks }}"
- debug: msg={{ delete_disk_images }}


- name: Delete Directory
  file:
    path: "{{ item.base_dir }}"
    state: absent
  register: delete_dir
  ignore_errors: true
  with_items: "{{ _iscsi.target.disks }}"
- debug: msg={{ delete_dir }}

