---
- name: Install Parted
  yum:
    name: parted
    state: present
  register: install_parted
- debug: msg={{ install_parted }}


- name: "Add New Partition /dev/sdb1"
  parted:
    device: /dev/sdb
    number: 1
    flags: [ lvm ]
    state: present
  register: add_partition
- debug: msg={{ add_partition }}


- name: Format the Partition
  filesystem:
    fstype: xfs
    dev: /dev/sdb1
  register: format_partition
- debug: msg={{ format_partition }}


- name: Creates Directory for iSCSI Connection
  file:
    path: "{{ iscsi_disk_base_dir }}/{{inventory_hostname}}_iscsidir"
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: yes
  register: create_directory
- debug: msg={{ create_directory }}


- name: Mount the Partition to
  mount:
    fstype: xfs
    src: /dev/sdb1
    path: "{{ iscsi_disk_base_dir }}/{{inventory_hostname}}_iscsidir"
    state: mounted
  register: mount_partition
- debug: msg={{ mount_partition }}

