---
- name: Install Packages for Ovirt Engine Python SDK
  package:
    name: "{{ item }}"
    state: present
  register: install_pkgs
  with_items:
    - libxml2-devel
    - python3-pip
- debug: msg={{ install_pkgs }}


- name: Install Wheel
  shell: |
    pip3 install wheel
  register: install_wheel
- debug: msg={{ install_wheel }}


- name: Install Ovirt Engine Python SDK
  shell: |
    pip3 install ovirt-engine-sdk-python==4.4.0
  register: install_python_sdk
- debug: msg={{ install_python_sdk }}


