---
- name: Uninstall Ovirt Engine Python SDK
  shell: |
    pip3 uninstall ovirt-engine-sdk-python -y
  register: uninstall_python_sdk
- debug: msg={{ uninstall_python_sdk }}


- name: Uninstall Packages for Ovirt Engine Python SDK
  package:
    name: "{{ item }}"
    state: absent
  register: uninstall_pkgs
  with_items:
    - python3-pip
    - libxml2-devel
- debug: msg={{ uninstall_pkgs }}

