---
- name: Install oVirt Engine Package Repository
  package:
    name: centos-release-ovirt45
    state: present
  register: install_ovirt_repo_pkgs
- debug: msg={{ install_ovirt_repo_pkgs }}
  when: print_debug == true


- name: Update Repository Configurations File for Rocky 9.x
  replace:
    path: "/etc/yum.repos.d/CentOS-{{ item.fn }}.repo"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
    backup: "{{ item.backup }}"
  register: change_required_config
  with_items:
    - { fn: "oVirt-4.5",           regexp: "$stream",  line: "9-stream",  backup: no }
    - { fn: "Storage-common",      regexp: "$stream",  line: "9-stream",  backup: no }
    - { fn: "OpenStack-yoga",      regexp: "$stream",  line: "9-stream",  backup: no }
    - { fn: "Messaging-rabbitmq",  regexp: "$stream",  line: "9-stream",  backup: no }
    - { fn: "NFV-OpenvSwitch",     regexp: "$stream",  line: "9-stream",  backup: no }
    - { fn: "Ceph-Pacific",        regexp: "$stream",  line: "9-stream",  backup: no }
    - { fn: "Gluster-10",          regexp: "$stream",  line: "9-stream",  backup: no }
    - { fn: "OpsTools",            regexp: "$stream",  line: "9-stream",  backup: no }
  # when: ansible_os_family == 'Rocky' and ansible_distribution_major_version|int == 9


- name: Update Caches for DNF Packages
  shell: |
    dnf makecache -y
  register: update_dnf_cache
- debug: msg={{ update_dnf_cache }}
  when: print_debug == true

