---
- name: Set Gluster Storage Domain to Maintenance Mode
  ovirt_storage_domain:
    name: "{{ _sd.gluster.name }}"
    host: "{{ hostvars[groups['hosts'][0]].ansible_hostname }}"
    data_center: "{{ _dc[0].name }}"
    state: maintenance
    wait: true
    auth: "{{ _ovirt.engine.auth }}"


- name: Unattach Gluster Storage Domain
  ovirt_storage_domain:
    name: "{{ _sd.gluster.name }}"
    host: "{{ hostvars[groups['hosts'][0]].ansible_hostname }}"
    data_center: "{{ _dc[0].name }}"
    state: unattached
    wait: true
    auth: "{{ _ovirt.engine.auth }}"


- name: Remove Gluster Storage Domain
  ovirt_storage_domain:
    name: "{{ _sd.gluster.name }}"
    host: "{{ hostvars[groups['hosts'][0]].ansible_hostname }}"
    data_center: "{{ _dc[0].name }}"
    state: absent
    format: true
    wait: true
    auth: "{{ _ovirt.engine.auth }}"

