---
- name: Create Locaal Storage Domain
  ovirt_storage_domain:
    name: jlocal-storage01
    host: co9-node03
    data_center: mydatacenter
    localfs:
      path: /ovirt-local-dir
    auth: "{{ _ovirt.engine.auth }}"

