---
- name: Disallow Service Ports If Firewalld is Running
  shell: |
    firewall-cmd --remove-service={dns,http,https}
    firewall-cmd --remove-port={6443/tcp,22623/tcp,1936/tcp,8080/tcp}
    firewall-cmd --runtime-to-permanent
  register: disallow_firewalld_service_port
  ignore_errors: true
- debug: msg={{ disallow_firewalld_service_port }}
  when: print_debug == true


- name: Disable Firewalld
  import_tasks: disable-firewall.yml


- name: Change SELinux Policy If It is Enabled
  shell: |
    setsebool -P httpd_can_network_connect off
    setsebool -P httpd_graceful_shutdown off
    setsebool -P httpd_can_network_relay off
    setsebool -P nis_enabled off
    semanage port -a -t http_port_t -p tcp 6443
    semanage port -a -t http_port_t -p tcp 22623
    semanage port -a -t http_port_t -p tcp 1936
  register: config_dns_settings
  ignore_errors: true
- debug: msg={{ config_dns_settings }}
  when: print_debug == true


- name: Stop NGNIX
  systemd:
    name: nginx
    state: stopped
  register: stop_nginx
  ignore_errors: true
  until: stop_nginx is succeeded
  retries: 10
  delay: 10
- debug: msg={{ stop_nginx }}
  when: print_debug == true


- name: Delete NGINX Config a Line for OKD's MGR
  lineinfile:
    dest: "/etc/nginx/okd-mgr-nginx.conf"
    line: "^include /etc/nginx/okd-mgr-nginx.conf*"
    state: absent
  ignore_errors: true


- name: Delete NGINX Config File
  file:
    path: "/etc/nginx/{{ item }}"
    state: absent
  register: delete_nginx_config_file
  ignore_errors: true
  with_items:
    - "okd-mgr-nginx.conf"
- debug: msg={{ delete_nginx_config_file }}


- name: Rollback Required Settings for OKD Cluster to Nginx
  lineinfile:
    dest: "/etc/nginx/nginx.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  register: add_required_nginx_config
  ignore_errors: true
  with_items:
    - { regexp: "^        listen       8080",         line: "        listen       80;",           state: present }
    - { regexp: "^        listen       [::]*",        line: "        listen       [::]:80;",      state: present }


- name: Uninstall NGINX Packages
  package:
    name: "{{ item }}"
    state: absent
  ignore_errors: true
  with_items:
    - "nginx-mod-stream"

