---
- name: Verify the State of Postgres instance
  become_user: postgres
  shell: ( source {{ _pgsql.base_dir }}/.bash_profile ; {{ _common.pgsql_bin_dir }}/pg_ctl -V )
  register: verify_single_postgres_state
  args:
    chdir: "{{ _pgsql.base_dir }}"
    executable: /bin/bash
- debug: msg={{ verify_single_postgres_state }}

