---
- name: Alternative Python version
  shell: |
    update-alternatives --install /usr/bin/python python {{ yum_python_version }} 1
    alternatives --set python {{ yum_python_version }}
  register: alternative_python_version


- name: Install Common Prerequisties RPM Packages for Postgres
  package:
    name: "{{ rh_install_pkgs }}"
    state: present
  vars:
    ansible_python_interpreter: "{{ yum_python_version }}"


- name: Install IPAddress PIP3 Module
  shell: |
    pip3 install ipaddress
  register: install_pip3_ipaddress
  when: hostvars[inventory_hostname].ansible_distribution_major_version|int <= 7


- name: Install the PostgreSQL Packages
  package:
    name: "{{ item }}"
    state: present
    disable_gpg_check: true
  async: 180
  poll: 5
  vars:
    ansible_python_interpreter: "{{ yum_python_version }}"
  with_items:
    - postgresql
    - postgresql-server
    - postgresql-jdbc
    - postgresql-contrib
    - python3-psycopg2

