---
- name: Stop PostgreSQL Systemd Service
  systemd:
    name: postgresql
    state: stopped
    daemon_reload: yes
  register: stop_postgresql_service
  ignore_errors: true
  async: 60
  poll: 5


- name: Uninstall Postgres Packages
  package:
    name: "{{ item }}"
    state: absent
    disable_gpg_check: true
  register: uninstall_pgsql_pkgs
  ignore_errors: true
  with_items:
    - postgresql
    - postgresql-server
    - postgresql-jdbc
  vars:
    ansible_python_interpreter: "{{ yum_python_version }}"


- name: Delete PostgreSQL Configuration Files and Data Directory
  file:
    path: "{{ item }}"
    state: absent
  register: delete_postgres_config
  ignore_errors: true
  with_items: "{{ delete_file_list }}"


- name: Uninstall PostgreSQL Prerequesties Packages
  package:
    name: "{{ rh_uninstall_pkgs }}"
    state: absent
    skip_broken: yes
  register: uninstall_pkgs
  ignore_errors: true
  vars:
    ansible_python_interpreter: "{{ yum_python_version }}"


- name: Reload Systemd Daemon
  systemd:
    daemon_reload: yes
  register: reload_sysemd_daemon
  ignore_errors: true
  async: 60
  poll: 5


- name: Alternative Python Version
  shell: |
    /usr/sbin/update-alternatives --install /usr/bin/python python {{ yum_python_version }} 1
    /usr/sbin/alternatives --set python {{ yum_python_version }}
  register: alternatives_python3
  ignore_errors: true
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'

